<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>Interactive Particle Logo - js do it</title>
<meta name="Description" content="" />
<meta name="Keywords"  content="" />

<link rel="stylesheet" type="text/css" media="screen,print" href="{{ url('css/style.css') }}" />
</head>
<body>
<!-- generated by: jsdo.it - http://jsdo.it/TaminoMartinius/Interactive-Particle-Logo -->
<!-- Copyright TaminoMartinius - http://jsdo.it/TaminoMartinius -->
<!-- All Rights Reserved. -->
<html>
    <head>
  	    <title>ParticleSlider</title>
    </head>
    <body id="particle-slider">
        <div class="slides">
        <div id="first-slide" class="slide" data-src="{{ url('img/ikt.png') }}">
      	</div>
    	</div>
  		<canvas class="draw"></canvas>
    </body>
</html>


        <script src="http://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.5/dat.gui.min.js"></script>
<script type="text/javascript" src="index.js"></script>
</body>
</html>
